---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-project-template
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app.kubernetes.io/name: fastapi-project-template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastapi-project-template 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                elasticsearch.k8s.elastic.co/cluster-name: topolvm-test
            topologyKey: kubernetes.io/hostname
      containers:
        - name: fastapi-project-template 
          image: leo-python:3.8-buster
          volumeMounts:
            - mountPath: /test1
              name: my-volume
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: topolvm-pvc
